### ISSUE TITLE
program crashes when selecting borderlands 2 after changing mouse sensitivity

### ISSUE THREAD

**Issue by staticanimal** [biggestcookie/Borderlands-Sensitivity-Changer#1]
i open the program, select borderlands 2, it tries to load my profile.bin and then immediately errors out.
error goes as follows

"Backing up profile.bin to profile.bin.bak
Traceback (most recent call last):
  File "main.py", line 49, in <module>
  File "main.py", line 17, in main
  File "offset.py", line 45, in get_current_sens
IndexError: bytearray index out of range
[13860] Failed to execute script main"

this started occurring after i attempted to set my mouse sensitivity to 7, somehow setting it to 60 ingame. changing the mouse sensitivity in the game does not fix the issue

**Comment by biggestcookie** [comment]
Hi! I apologize for getting to this so late (2 years), my notifications were misconfigured until recently. 
I don't suppose you're still looking for assistance? If not I'll close this issue.

**Comment by staticanimal** [comment]
i don't need any further help with this, you're free to close the issue.
